name: "AI Code Review"
description: "Run AI-based code review on pull requests using OpenAI GPT and GitHub API"
author: "test"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API access"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for calling ChatGPT"
    required: true
  GITHUB_REPOSITORY_OWNER:
    description: "Repository owner (organization or user)"
    required: true
  GITHUB_REPOSITORY_NAME:
    description: "Repository name"
    required: true
  PR_NUMBER:
    description: "Pull request number to review"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build AI review tool
      shell: bash
      run: go build -o ai-review main.go

    - name: Run AI review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
      run: ./ai-review

