name: "AI Code Review"
description: "Run AI-based code review on pull requests using OpenAI GPT and GitHub API"
author: "test"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API access"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for calling ChatGPT"
    required: true
  GITHUB_REPOSITORY_OWNER:
    description: "Repository owner (organization or user)"
    required: true
  GITHUB_REPOSITORY_NAME:
    description: "Repository name"
    required: true
  PR_NUMBER:
    description: "Pull request number to review"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run action
      run: "./repotest"
      shell: bash
